#!/usr/bin/env bash

signal=$(iwconfig wlp2s0 | grep -i Link)
signalsplit=($signal)


STRENGTH=$(echo "${signalsplit[3]}" | tr -dc '0-9')


if (( $STRENGTH > 56 )); then
    echo "──────"
elif (( $STRENGTH > 42 )); then
    echo "─────"
elif (( $STRENGTH > 28 )); then
    echo "────"
elif (( $STRENGTH > 14 )); then
    echo "───"
else
    echo "──"
fi 
