#!/bin/bash

# A simple script to display battery percent
# Taken from Anachron i3blocks
# I only slightly modify this script to add an option to show icon
# I also remove the i3blocks specify script
# To make this works with tint2 executor, polybar custom script, dzen2 feeder, conkybar, lemonbar feeder, dunst notify, etc.
# 'battery -i' = with icon, 'battery' = text only
# Cheers!
# Addy

BATTERY=1
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

if (( $BATTERY_POWER > 80 )); then
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotOne.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotTwo.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotThree.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotFour.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotFive.png)
elif (( $BATTERY_POWER > 60 )); then
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotOne.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotTwo.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotThree.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotFour.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/chargedDot.png $HOME/.config/conky/WIP/assets/batt/dotFive.png)
elif (( $BATTERY_POWER > 40 )); then
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotOne.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotTwo.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotThree.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/chargedDot.png $HOME/.config/conky/WIP/assets/batt/dotFour.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/chargedDot.png $HOME/.config/conky/WIP/assets/batt/dotFive.png)
elif (( $BATTERY_POWER > 20 )); then
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotOne.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotTwo.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/chargedDot.png $HOME/.config/conky/WIP/assets/batt/dotThree.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/chargedDot.png $HOME/.config/conky/WIP/assets/batt/dotFour.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/chargedDot.png $HOME/.config/conky/WIP/assets/batt/dotFive.png)
else
    $(ln -sf $HOME/.config/conky/WIP/assets/notChargedDot.png $HOME/.config/conky/WIP/assets/batt/dotOne.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/chargedDot.png $HOME/.config/conky/WIP/assets/batt/dotTwo.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/chargedDot.png $HOME/.config/conky/WIP/assets/batt/dotThree.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/chargedDot.png $HOME/.config/conky/WIP/assets/batt/dotFour.png)
    $(ln -sf $HOME/.config/conky/WIP/assets/chargedDot.png $HOME/.config/conky/WIP/assets/batt/dotFive.png)
fi 

