#
# ~/.zshrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Make Scripts GLOBAL
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/.local/bin"

# Set VIM as Editor
export VISUAL="vim"

# Aliases
## General
alias ls='ls --color=auto'

## Pacman
alias pcinstall='sudo pacman -S'
alias pcupdate='sudo pacman -Syu'
alias pcremove='sudo pacman -Rs'
alias pcclean='sudo pacman -Rs $(pacman -Qqdt)'

## Fonts
alias fontr='fc-cache -fvr'

## QOL 
alias vim="nvim"
alias mupdf="mupdf -C f6f6f6"

## Git
alias gita='git add .'
alias gitc='git commit -m '
alias gitp='git push'
alias gits='git status'

## Wifi
alias wifid='sudo ip link set wlp2s0 down'
alias wifiu='sudo ip link set wlp2s0 up'
alias macc='sudo macchanger -r wlp2s0'
alias macr='sudo macchanger -p wlp2s0'

# Oh-My-ZSH
# PATH
export ZSH=/home/plasma/.oh-my-zsh

# Theme
ZSH_THEME="clair"

# Corrections
ENABLE_CORRECTION="true"

# Source
source $ZSH/oh-my-zsh.sh

# if [[ ! ${DISPLAY} && ${XDG_VTNR} == 1 ]]; then
#    startx
#fi
